version: "3.8"
# https://intellipaat.com/community/67761/mounting-efs-to-aws-fargate-using-terraform-platformtaskdefinitionincompatibilityexception-error
services:
  express-app:
    build:
      context: ""
    container_name: express-app
    image: express-app
    volumes:
      - ./express-app:/app
    networks:
      - express_network
    ports:
      - "${APP_PORT}:8088"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
  database:
    build:
      context: mysql
    image: express_db
    container_name: express_db
    volumes:
      - express_db_volume:/var/lib/mysql
    networks:
      - express_network
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
  react-app:
    build:
      context: react-app
    image: react-app
    container_name: react-app
    networks:
      - express_network
    volumes:
      - ./react-app:/app
    ports:
      - "${REACT_APP}:3000"
networks:
  express_network:
    name: express_network
volumes:
  # need nfs
  express_db_volume: {}
