version: "3.8"

services:
  express-app:
    build:
      context: express-app
      dockerfile: Dockerfile
    container_name: express-app
    image: express-app-prod
    networks:
      - express_network
    ports:
      - "${APP_PORT}:8088"
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
      - AWS_REGION=${AWS_REGION}
      - APP_ENV=${SECRET_MANAGER_NAME}
  database:
    build:
      context: mysql
    image: express-db-prod
    container_name: express_db
    networks:
      - express_network
    volumes:
      - express_db_volume:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
  react-app:
    build:
      context: react-app
      dockerfile: Dockerfile
    image: react-app-prod
    container_name: react-app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - express_network
    volumes:
      - ./react-app:/app
    ports:
      - "${REACT_PORT}:80"
networks:
  express_network:
    name: express_network
volumes:
  express_db_volume: {}
