version: "3"

services:
  my_react_app:
    container_name: my_react_app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    ports:
      - 8081:80
    networks:
      - my_react_app_network

networks:
  my_react_app_network:
    name: my_react_app_network

